### ISSUE TITLE
multi.go partialClientConn UpdateState method should return error

### ISSUE THREAD

**Issue by EugenRommel** [Jille/grpc-multi-resolver#1]
# github.com/Jille/grpc-multi-resolver
../../../../pkg/mod/github.com/!jille/grpc-multi-resolver@v1.0.0/multi.go:54:41: cannot use pcc (type *partialClientConn) as type resolver.ClientConn in argument to resolverBuilder.Build:
	*partialClientConn does not implement resolver.ClientConn (wrong type for UpdateState method)
		have UpdateState(resolver.State)
		want UpdateState(resolver.State) error

**Comment by Jille** [comment]
Are you running grpc-go v1.41.0-dev?

I'm depending on their experimental APIs in grpc/internal, and they changed it (https://github.com/grpc/grpc-go/commit/1c598a11a4e503e1cfd500999c040e72072dc16b) :(

**Comment by Jille** [comment]
Closing because I assume this is stale as of previous release.
